### ISSUE TITLE
New marketplace experience

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/hacktoberfest-no-code#100]
### Description
The project aims to create a fresh and improved marketplace experience with enhanced features, design, and usability.
### Impact
The new marketplace experience will likely result in increased user satisfaction, easier navigation, and potentially higher adoption rates, contributing to a more vibrant and successful marketplace ecosystem.

### Tasks

- [x] Make it easier for people to ask questions in community
- [x] Make it easier for devs to find docs
- [x] Make technical setup warnings marketer-friendly
- [x] New cards design for marketplace items
- [x] Redesign the details page

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>
